# Generated by Django 4.2.8 on 2023-12-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdata',
            old_name='temperature',
            new_name='endTemperature',
        ),
        migrations.AddField(
            model_name='inputdata',
            name='startTemperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputdata',
            name='thremalCapacity',
            field=models.IntegerField(default=0),
        ),
    ]
