# Generated by Django 4.2.8 on 2023-12-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_temperature_inputdata_endtemperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dateReport',
            field=models.DateTimeField(null=True),
        ),
    ]
